# Generated by Django 4.0.2 on 2022-02-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_kumuz'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='content1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kumuz',
            name='content1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='content1',
            field=models.TextField(blank=True),
        ),
    ]
