# Generated by Django 4.0.2 on 2022-03-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_makal_pikir_tagam_delete_aiakkim_delete_baskim_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pikir',
            old_name='content',
            new_name='title',
        ),
    ]
